### PR TITLE
Add knowledge base feature/mapping lookup

### PR DESCRIPTION
**Pull request by kostko**
Requires genialis/resolwe-bio#162 deployed on the backend.

See #69.

Example use:
```python
# Get a list of mappings.
resolwe.mapping.filter(source_db='A', source_id__in=['foo', 'another'])
# Get a list of features.
resolwe.feature.filter(source='UCSC', query=['A1BG'])
```

### CODE REVIEW

**Comment by jkokosar** [comment]
I have tested the functionality of the mapping/feature filters:

1) resolwe.mapping.filter()
 - is there a list of available filter parameters?
 - `source_id__in` can this be `query`?
 -  is there a way to limit which  'target_db' is returned?

2) resolwe.feature.filter()
 - is there a list of available filter parameters?
 - When I get the features retured using the filter(), how can I access the object fields (organism, description, aliases..)? Is this not yet supported?

**Comment by jkokosar** [comment]
@dblenkus Please review

**Comment by kostko** [comment]
> is there a list of available filter parameters?

Yes, at the moment you can query by `source_db`, `source_id`, `target_db` and `target_id`. Should we also allow filtering by `relation_type`?

> source_id__in can this be query?

Yes, we can change this.

> is there a way to limit which 'target_db' is returned?

Yes, querying by `target_db` should work.

> is there a list of available filter parameters?

Yes, currently `query` (genes) and `source`.

> When I get the features retured using the filter(), how can I access the object fields (organism, description, aliases..)? Is this not yet supported?

I've updated the branch, it should work now using attribute access.

**Comment by kostko** [comment]
I'll update the backend so that mapping search is also handled by elastic search, so that we can have a separate search endpoint and a separate rest endpoint for updating mappings via the API.

**Comment by jkokosar** [comment]
Should we also allow filtering by relation_type?

Not required at the moment.

**Comment by kostko** [comment]
Updated the API. It now requires genialis/resolwe-bio#168 and genialis/genialis-base#192.

**Pull request merged**
