### PR TITLE
Fix failed query if number of samples is too large

### LINKED ISSUE #256: CollectionTables unable to fatch metadata from large collection
During downloading of metadata from a large collection (it has 1220 samples) you get the following exception:
```
/home/robert/git/resolwe-bio-py/venv/bin/python /home/robert/git/resolwe-bio-py/foo.py
Traceback (most recent call last):
  File "/home/robert/git/resolwe-bio-py/src/resdk/exceptions.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/robert/git/resolwe-bio-py/venv/lib/python3.8/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/home/robert/git/resolwe-bio-py/venv/lib/python3.8/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
slumber.exceptions.HttpClientError: Client Error 414: https://app.genialis.com/api/sample

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robert/git/resolwe-bio-py/foo.py", line 6, in <module>
    meta = col_tab.meta
  File "/home/robert/git/resolwe-bio-py/src/resdk/collection_tables.py", line 176, in meta
    return self._load_fetch(META)
  File "/home/robert/git/resolwe-bio-py/src/resdk/collection_tables.py", line 354, in _load_fetch
    data = self._download_metadata()
  File "/home/robert/git/resolwe-bio-py/src/resdk/collection_tables.py", line 488, in _download_metadata
    meta = pd.DataFrame(None, index=[s.name for s in self._samples])
  File "/home/robert/git/resolwe-bio-py/src/resdk/collection_tables.py", line 251, in _samples
    return list(
  File "/home/robert/git/resolwe-bio-py/src/resdk/query.py", line 145, in __len__
    return self.count()
  File "/home/robert/git/resolwe-bio-py/src/resdk/query.py", line 222, in count
    count_query._fetch()
  File "/home/robert/git/resolwe-bio-py/src/resdk/query.py", line 196, in _fetch
    items = self.api.get(**filters)
  File "/home/robert/git/resolwe-bio-py/src/resdk/exceptions.py", line 34, in wrapper
    raise ResolweServerError(exception.content)
resdk.exceptions.ResolweServerError: b'<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body>\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
```
The root of the problem is in `_samples` where we filter samples by ids which results in a large `id__in` filter/argument and consequently, a large URL send to the server.

### PR DESCRIPTION
**Pull request by JureZmrzlikar**
Fixes #256

### CODE REVIEW

**Review by mzganec — CHANGES_REQUESTED** [review]
The length of returned metadata `DataFrame` is incorrect. In the TCGA BRCA collection:
```
>>> col.samples.count()
1222
>>> len(tables.meta)
1252
```
Ideally, we would like to see the two numbers match.

**Comment by robertcv** [comment]
We decided to move forward with those changes. A few additional requests are: 
- Use `expressions_id` instead of `sample_id` so that it's more clear that those ids are from the platform.
- Use the general logger module to show the warnings.

And I also have some personal notes:
- Check for duplicates when calling `id_to_name` which will be often used by end-users.
- I am not sure how but we should rename `id_to_name` and/or `id_to_symbol` as they are very similar and they could both be interpreted the wrong way.

**Comment by mzganec** [comment]
> I am not sure how but we should rename id_to_name and/or id_to_symbol as they are very similar and they could both be interpreted the wrong way.

In `pandas` vocabulary these could become `index_to_names` and `columns_to_symbols`.

**Comment by JureZmrzlikar** [comment]
> In `pandas` vocabulary these could become `index_to_names` and `columns_to_symbols`.

@robertcv Do you agree on this? If so, i can start working on this.

**Comment by JureZmrzlikar** [comment]
@robertcv @mzganec 
I've left out the renaming from `sample_id` to `expressions_id` for now, but otherwise included your suggestions. Please review again.

**Review by mzganec — APPROVED** [review]
Works well, thanks!

**Pull request merged**
