### PR TITLE
Fix resolwe.run docstring

### PR DESCRIPTION
**Pull request by JureZmrzlikar**

### CODE REVIEW

**Comment by mstajdohar** [comment]
Nice work, the code is great. Please add tests.

**Comment by JureZmrzlikar** [comment]
This PR only changes one docstring and two pylint errors. I don't think that tests should be required for this. But yes - the other PR will significantly increase coverage, as soon as e2e testsing is supported.

**Comment by mstajdohar** [comment]
Tests should be added because they were not written in the first place (for the three lines that you changed). Are this lines covered in e2e tests? If not, we should write a unit test for this.

**Comment by JureZmrzlikar** [comment]
Yes, they are covered in e2e tests.

**Comment by dblenkus** [comment]
The code with missing parenthesis shouldn't work. Does e2e test catch this?

**Comment by JureZmrzlikar** [comment]
Tests cover changed lines, so i believe they would fail.

**Comment by mstajdohar** [comment]
If we have a test for this in e2e it LGTM.

**Pull request merged**
